- README.md
To test:
1. Read the latest changes to the README.md and make sure that nothing vital is missing and that there is no wrong information on the text.
> UHF-9 Add short instrcutions on how to use as base theme

- templates/content/node--article.html.twig
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/58
- When the one above is approved, you may approve this one as well
> UHF-917 URLs

- templates/field/field--field-unit-main-image-url.html.twig
Make sure the unit external images still work.
Check also these:
https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/17
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/71
> UHF-1089: Refactor the twig extension name

- hdbt.theme
> UHF-1406: Relative URL

- hdbt.theme
- modules/hdbt_content/hdbt_content.module
- templates/paragraphs/paragraph--unit-search.html.twig
- templates/views/views-infinite-scroll-pager--unit-search.html.twig
- templates/views/views-view--unit-search.html.twig
Instructions: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/90
> UHF-949: Unit search

- templates/block/block--footerbottomnavigation.html.twig
- templates/misc/icon.twig
- templates/navigation/links--language-block.html.twig
- templates/paragraphs/paragraph--gallery-slide.html.twig
- templates/paragraphs/paragraph--gallery.html.twig
Just check [the files](https://github.com/City-of-Helsinki/drupal-hdbt/pull/86/files) and [helfi-platform PR](https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/31)
> UHF-796: Fixed minor issues with accessibility.

- hdbt.theme
To test:
1. Checkout the branch
2. Create landing page without a paragraph
3. Make sure things don't break after saving :)
4. Add unit search paragraph to the landing page and add it a hero block also.
5. Make sure the gray background on the unit search block continues seamlessly under the hero
> Modify node preprocess so that it won't die if there is no paragraph

- config/install/block.block.eucookiecomplianceblock.yml
- modules/hdbt_content/hdbt_content.module
- modules/hdbt_content/hdbt_content.routing.yml
- modules/hdbt_content/src/Controller/CookieConsentController.php
- modules/hdbt_content/templates/cookie-consent-intro.html.twig
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/111
> UHF-1592 Cookies

- hdbt.theme
- modules/hdbt_content/hdbt_content.module
- modules/hdbt_content/src/Plugin/Block/HeroBlock.php
Instructions in this PR https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/130
Also check: 
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/130
https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/60
> UHF-1728 Color palette base field

- templates/views/views-view--service-list.html.twig
Check instructions from the other PRs:
https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/34
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/77
https://github.com/City-of-Helsinki/drupal-helfi/pull/192
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/82
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/157
> UHF-2520: Change service list string results to services

- modules/hdbt_content/hdbt_content.tokens.inc
Instructions in https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/217
> UHF-3206: Shareable image token

- README.md
- hdbt.info.yml
- translations/fi.po
- translations/sv.po
How to test: 
- Checkout this branch in some instance or run `composer require drupal/hdbt:dev-UHF-X_hdbt_translations`
- In shell run: `drush cr && drush locale:check` and check that the output has these lines: 
```
>  [notice] Checked fi translation for hdbt.
>  [notice] Checked sv translation for hdbt.
```
- In the shell run:  `drush locale:update`  and check that the output has these lines: 
```
>  [notice] Imported fi translation for hdbt.
>  [notice] Imported sv translation for hdbt.
```
> Added ability to translate HDBT theme specific translations.

- README.md
> UHF-X: Add translation checking documentation

- hdbt.theme
How to test:
1. `make drush-cr`
2. Make sure when you edit content you no longer get the wsod.
> Fix for white screen of death when editing content

- hdbt.theme
- translations/fi.po
- translations/sv.po
1. Get an instance with TPR content up and running. Preferably kymp.
2. `make shell`
3. `drush locale:check && drush locale:update && drush cr`
4. Go to https://helfi-kymp.docker.so/sv/stadsmiljo-och-trafik/parkering/boendeparkering and open "Detaljer" accordion
- Check that all information has been translated in to Swedish
> UHF-X Errand service translations

- templates/module/helfi_tpr/tpr-unit.html.twig
Check https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/91 for instructions.
> UHF-4163: Add group menu for TPR unit's sidebar

- modules/hdbt_content/hdbt_content.tokens.inc
* Check for theme existence before loading the theme
> UHF-X Check for hdbt theme

- templates/module/helfi-news-item/node--news-item.html.twig
Check [UHF-5459 on Etusivu](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pulls)
> UHF-5459: Radioactivity most read news

- .github/pull_request_template.md
* Add a slot to remember check stuff with designers
* Modified PR template
* Check the heading below for an example
One of the checkboxes below needs to be checked (`[x]`)
One of the checkboxes below needs to be checked (`[x]`)
> UHF-X: Improve PR template

- templates/paragraphs/paragraph--hero.html.twig
see above
* An unnecessary typo was removed
* Unused classes removed
* Types of supported hero classes were clarified in template
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_clean_hero_template`
* Check that code looks sane, test that hero works still
One of the checkboxes below needs to be checked (`[x]`)
> UHF-X_clean_hero_template

- templates/layout/page--user--login.html.twig
- templates/layout/page--user--reset.html.twig
Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/153
> UHF-6006: User access

- hdbt.libraries.yml
- src/js/nav-global-toggle.js
- src/scss/06_components/navigation/global/__index.scss
- src/scss/06_components/navigation/global/_js_mobile-navigation.scss
- src/scss/06_components/navigation/global/_menu-toggle.scss
- templates/block/block--mobile-navigation.html.twig
- templates/layout/page.html.twig
Create a new hamburger button for global navigation functionality
* Added foundation on which to build global navigation.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-5869_global_hamburger`
> UHF-5869 global hamburger

- modules/hdbt_content/hdbt_content.tokens.inc
Part of REKRY PR: https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/56
> UHF-5306: Job listing og tags

- src/js/nav-global.js
- src/scss/01_variables/_typography_variables.scss
- src/scss/06_components/block/_language-switcher.scss
- src/scss/06_components/navigation/global/_menu-toggle.scss
- src/scss/06_components/navigation/global/_mmenu.scss
- Use real API
- fall back to nojs menu if loading fails.
- focuses to correct page
TODO , SLACK
* Make sure you have to etusivu and another instance up and running the global menu codes and module (See Slack)
**In the other instance**
* `composer require drupal/hdbt:dev-UHF-6356_api_merge`
* [X ] This PR does not need designers review
> UHF-6356: connect to api

- src/js/nav-global.js
- src/scss/06_components/navigation/global/_mmenu.scss
We need new stuff for the upcoming global navigation structure.
* Mobile menu
* Mobile fallback menu
* Megamenu
TODO things will be documented in [UHF-6181](https://helsinkisolutionoffice.atlassian.net/browse/UHF-6181)
* Mobile menu, enhanced with js (coded by Sakari)
* Language menu
* Main global menu
* header-top-menu aka mobile-footer
* Logo with link
* Mobile fallback menu
* Language menu
* Main global menu
* header-top-menu aka mobile-footer
* Logo with link
* Megamenu
* Fixes to header
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-6017-jsmenu`
* Make sure you're running the HDBT global navigation module
* Check that you have menu items
TBD …
> UHF-6017 Mobile jsmenu

- src/js/nav-global.js
- src/scss/06_components/navigation/global/_menu-toggle.scss
- src/scss/06_components/navigation/global/_mmenu.scss
* Hide page content when mobile menu is opened to avoid tabbing to background stuff
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-6712_fix_nav_accessibility_issues`
* Run `npm run build` in hdbt folder
> UHF-6712: Fix global nav accessibility issues

- templates/block/block--external-menu-block-fallback.html.twig
* Added header_top_navigation twig block to fallback menu template
* Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/123
> UHF-6762 Frontpage navigation templates

- modules/hdbt_content/hdbt_content.module
* Added alter for the sidebar allowed entities list.
> Added alter for the sidebar allowed entities list.

- hdbt.theme
* Added attribute to menu item if it's set in menu link content but not found in menu item.
> UHF-X Lang attribute to fallback menu

- hdbt.theme
* Check if the current project is not in environments list before handling Etusivu links
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-6960_fix_for_non_helfi_project`
* `$config['helfi_api_base.environment_resolver.settings']['project_name'] = 'my_awesome_project'; ` 
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/381
> UHF-6960: Fix for non helfi project

- modules/hdbt_content/hdbt_content.install
* Check for block configuration existence before installing the blocks.
> UHF-X Fix for footer block install

- src/js/calculator/home_care_client_payment.js
- src/js/calculator/home_care_service_voucher.js
- src/js/calculator/house_cleaning_service_voucher.js
redundant `that = this`  closure variable removed. Arrow functions provide all the closures needed for this. 
* `make fresh`
> UHF-7029: redundant this=that removed.

- templates/misc/metadata-wrapper.twig
* Added check for metadata wrapper not to print empty values.
* Check instructions from the Rekry PR.
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/125
> UHF-7444: Add check for empty array item for metadata wrapper template

- templates/field/field--tpr-unit--distance.html.twig
- templates/module/helfi_tpr/tpr-unit--minimal.html.twig
- translations/fi.po
- translations/sv.po
> Fixed translation and span div issue

- hdbt.theme
* Converted theme path to run via the file create url service.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_theme_path_hotfix`
> UHF-X Theme path hotfix

- templates/layout/maintenance-page.html.twig
- templates/layout/page--401.html.twig
- templates/layout/page--404.html.twig
- templates/layout/page--user--login.html.twig
* Fixed the theme path in page templates.
> UHF-X Theme path fix

- hdbt.libraries.yml
serving old version. Try adding new version number to fix the problem
> test with a proper version number

- src/scss/06_components/paragraphs/_banner.scss
* Added logical properties support for Banner paragraph
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8222-Banner_paragraph_language_support`
[UHF-8222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8222: Logical properties support for Banner paragraph

- src/scss/06_components/paragraphs/_liftup-with-image.scss
* Added RTL language support for Liftup with image paragraph
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8221_Liftup_with_image_paragraph_language_support`
[UHF-8221]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8221: Liftup with image language support

- webpack.svgToSprite.js
* [Fixed sonarcloud issues with webpack.svgtosprite.js](https://github.com/City-of-Helsinki/drupal-hdbt/commit/b1aba7c42dcc8d82ea53c074bca3d30d8d334797)
> UHF-X Code fixes

- src/scss/03_generic/_lang.scss
- src/scss/06_components/paragraphs/_accordion.scss
- src/scss/06_components/paragraphs/_phasing.scss
* Added support for RTL language by using the CSS logical properties.
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8227_accordion-language-support`
* Run `npm run build` inside the `hdbt` theme, because this doesn't include built assets.
[UHF-8227]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8227 Accordion language support

- src/scss/06_components/pages/_news-page.scss
* Added RTL language support for News listing. 
* Includes paragraphs Latest and Top news, and also News page/feed at `/fi/uutiset`.
* **MISSING**: RTL support for Arrow icon directions and animations.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8224_News_paragraphs_language_support`
* [UHF-8224: RTL language support for Latest news](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/301)
[UHF-8224]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8224: News listing language support

- templates/paragraphs/paragraph--contact-card.html.twig
- translations/fi.po
- translations/sv.po
* Changed field label translations to run trough `t()`
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7413_Change_translate_method`
* [UHF-7413: Labels visibility to hidden](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/500)
[UHF-7413]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7413: Change translate method

- README.md
* Documentation was updated to include more information.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/684
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/221
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/135
[UHF-4905]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-4905 hdbt documentation

- templates/paragraphs/paragraph--hero.html.twig
* Removed reference to removed field_hero_bg_color
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_field_hero_bg_color_removal`
> UHF-X: Removed reference to removed field_hero_bg_color

- hdbt.theme
Issue: https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-940
Added cacheing for config as we observed from profiling that the function is called numerous times.
> Adding static cache in _hdbt_set_site_information

- templates/content/node--announcement--default.html.twig
- templates/paragraphs/paragraph--district-and-project-search.html.twig
Minor accessibility problems.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_fix_minor_accessibility_issues`
> Uhf x fix minor accessibility issues

- package-lock.json
- package.json
* When trying to commit on hdbt I got an error that says `cannot find module bubble-sort.mjs`. This PR fixes the error.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_css_declaration_sorter_fix`
> UHF-X Fix issue with postcss giving error about module missing

- templates/module/helfi_tpr/tpr-service-lower-content.html.twig
* Use the new checkbox field value in the template to hide the service points.
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/587
[UHF-8717]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8717: Hide service points if the checkbox is checked.

- templates/module/helfi_tpr/tpr-unit.html.twig
- translations/fi.po
- translations/sv.po
* Translated Contact information in TPR Units.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_tpr_unit_translations`
* Run `make shell`
* In shell, run: `drush locale:check; drush locale:update; drush cr`
> UHF-X Translated Contact information in TPR Units.

- hdbt.info.yml
- hdbt.theme
- templates/navigation/menu--external-menu--fallback.html.twig
- templates/navigation/menu--external-menu--mega-menu.html.twig
- templates/navigation/menu--mobile.html.twig
- templates/navigation/menu.html.twig
* Remove deprecated code.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9113-drupal10`
* City-of-Helsinki/drupal-helfi-platform-config/pull/617
* City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/462
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Drupal 10 compatibility

- .github/workflows/v6-sync.yml
* Added main -> v6 sync action
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Added hdbt v6-sync github action.

- hdbt.libraries.yml
* Updated job search library version
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9321_update_job_search_version`
[UHF-9321]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9321: Updated job search library version

- README.md
> UHF-X: update readme with react instructions.

- templates/paragraphs/paragraph--maternity-and-child-health-clini.html.twig
* Check installing instructions from the SOTE PR.
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/729
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/867
[UHF-9192]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9192: Add fallback search for maternity and child health clinics search

- templates/module/helfi_tpr/tpr-unit--after-school-activity-card.html.twig
- templates/module/helfi_tpr/tpr-unit--minimal.html.twig
- translations/fi.po
- translations/sv.po
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/548
[UHF-9230]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9230: after school activity search card

- .github/workflows/visual.yml
* Changed the text for the visual regression error text.
> UHF-X Visual regression error text

- hdbt.theme
* Fixed 'Call to a member function getTotalPages() on null' error.
> UHF-X Pager check

- src/js/hds-cc/hds-cc.js
- src/js/hds-cc/helfi_cookiesettings.json
> Uhf 9675 cookie banner rebased commits

- .github/pull_request_template.md
* Updates to this template
[UHF-9711]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9711: update PR template

- .github/workflows/visual.yml
* Sleep 10s after starting containers
> UHF-X Visual regression sleep

- src/js/hds-cc/hds-cc.js
- src/js/hds-cc/hds-cc_translations.js
- src/js/hds-cc/template.js
- src/scss/styles.scss
- templates/misc/cookie-container.html.twig
* Code needed some refactoring
* Code was refactored
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9791_clean_code`
[UHF-9791]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9791: UHF-9791: Refactor javascript code to be more readable

- src/js/hds-cc/deleteCookie.js
- src/js/hds-cc/hds-cc.js
- src/js/hds-cc/hds-cc_translations.js
- src/js/hds-cc/helfi_cookiesettings.json
- src/js/hds-cc/monitorAndCleanBrowserStorages.js
- src/scss/cookie-consent.scss
- templates/layout/html.html.twig
- templates/misc/cookie-container.html.twig
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9485_cookie_sniffing`
[UHF-9485]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9485 cookie sniffing

- src/js/hds-cc/cookieHandler.js
- src/js/hds-cc/hds-cc.js
- src/js/hds-cc/helfi_cookiesettings.json
- src/js/hds-cc/monitorAndCleanBrowserStorages.js
- templates/misc/cookie-container.html.twig
> UHF-9796 cookie banner cleanup

- hdbt.libraries.yml
* Fix js preprocess errors.
- Check that all js loads correctly (cookie banner should be visible).
[UHF-10398]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10398: Add minified: true to tabbable library

- .github/workflows/npm-audit.yml
- package-lock.json
- package.json
* Checked and merged renovate PRs if they were ok to be merged.
[UHF-10660]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10660 NPM updated #2

- src/scss/06_components/__index.scss
- src/scss/06_components/_eu-cookie-compliance-banner.scss
- templates/misc/eu_cookie_compliance_popup_info.html.twig
- templates/module/hdbt_cookie_banner/cookie-policy.html.twig
* Added a template override for the cookie policy page.
* Added deprecation comments to EU cookie compliance styles
* Check installation and testing instructions from [Helfi Platform config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/821)
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/821
[UHF-10738]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10738 Cookie policy

- backstop/backstop_dynamic_config.js
Fixed the selector for the announcements block.
> UHF-X Announcement test fix

- templates/component/hero.twig
Add missing condition to render hero description.
[UHF-10771]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10771: Add missing if condition

- hdbt.theme
- templates/content/external-entity--helfi-hearings.html.twig
We don't want finnish hearings on english page any more
> UHF-10887: remove the hearings on wrong language -feature

- templates/media/media--remote-video.html.twig
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/884
[UHF-10406]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10406: Check if video src is null

- translations/sv.po
* Check installation instructions from the [helfi_platform_config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/890).
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/890
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1166
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1630
[UHF-11222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11222: Language support for the curated event list

- templates/module/helfi_tpr/tpr-unit-contact-information.html.twig
clean up the code a bit [UHF-11597](https://helsinkisolutionoffice.atlassian.net/browse/UHF-11597)
[UHF-11597]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use variable instead

- src/scss/05_objects/_button.scss
* Added comment to button.scss as a result of the ticket
[UHF-11765]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11765: Added comment to button.scss and fixed linter errors

- hdbt.theme
- templates/media/media--hel-map.html.twig
- templates/media/media--helfi-chart.html.twig
- templates/media/media--remote-video.html.twig
* Removed preprocess functions for map, chart and remote video paragraphs
* Moved them to platform config
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11565 `
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/976
[UHF-11565]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11565: Changed how iframe title is set for map, chart and video

- templates/module/helfi_tpr/tpr-service.html.twig
* Added logic to hide or show errand services on service page based on new boolean field
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11924`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/982
[UHF-11924]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11924: Added logic to show or hide errand services based on boolean value

- templates/paragraphs/paragraph--unit-contact-card.html.twig
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11812 `
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1008
[UHF-11812]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11812: Added aria-label for unit contact card link

- hdbt.theme
- templates/paragraphs/paragraph--event-list.html.twig
- templates/paragraphs/paragraph--health-station-search.html.twig
- templates/paragraphs/paragraph--job-search.html.twig
- templates/paragraphs/paragraph--maternity-and-child-health-clini.html.twig
- templates/paragraphs/paragraph--ploughing_schedule.html.twig
It seems that school search script is never being loaded. This fixes it.
> Actually load the school search script

- templates/paragraphs/paragraph--unit-contact-card.html.twig
* Change the aria-label to aria-labelledby setup in unit contact cards
* Check installation instructions from the [helfi_platform_config](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1066).
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1362
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1066
[UHF-12141]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12141: Unit contact card more link aria-label changes

- hdbt.theme
* Moved CSP rules from global config to proper context in code.
* See installation and testing instructions in https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1068 
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1068
* https://github.com/City-of-Helsinki/drupal-kaupunkitieto/pull/171
* https://github.com/City-of-Helsinki/drupal-infofinland/pull/477
[UHF-11974]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11974: Adding CSP directives needed for Matomo.
