City-of-Helsinki/drupal-hdbt

hdbt.theme
templates/paragraphs/paragraph--gallery.html.twig

How to test: 
- Checkout this branch and go to https://helfi.docker.sh/fi/esimerkkisivu and check that the gallery thumbnails have alt texts

UHF-1473: Thumbnail alts

---

hdbt.theme

Converted menu block id check to handle subtheme menu blocks as well.

UHF-3150: Sidebar

---

hdbt.theme
modules/hdbt_content/hdbt_content.module
templates/layout/page.html.twig

How to test on any running local instance:
- Run `composer require drupal/hdbt:dev-UHF-3239_missing_sidebar`
- `make drush-cr`
- Check that sidebar is shown for the non super-admin user in basic page

UHF-3239: Missing sidebar

---

templates/content/tpr-errand-service.html.twig

To test:
1. Run these on KYMP. It has a visible issue here.
2. `composer require drupal/hdbt:dev-UHF-X_remove_duplicate_errand_service`
3. `make drush-cr`
4. Go to https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/pysakointi/asukaspysakointi and make sure the errand service information is written only once on the site.

UHF-X: Remove duplicate errand service information

---

modules/hdbt_content/hdbt_content.module

Removed menu link parent check when viewing basic page with menu links. The functionality changes from first level basic page not showing the sidebar menu to first level basic page Showing the sidebar menu.

UHF-X Menu first level sidebar

---

templates/module/helfi_tpr/tpr-service-channel.html.twig

[UHF-3552](https://helsinkisolutionoffice.atlassian.net/browse/UHF-3552)
With the help of the table of contents (ToC) feature , a problem was spotted where service channel headings were set to H2 and became visible in ToC. This caused unwanted repeating of same heading content on identical heading level. 
On SOTE this `h2` level is wanted as there are no previous `h2` headings like in other instances.
* The template where this issue is visible was moved to HDBT module for clearer editing in future.
* The template under HDBT now supports custom heading level if set but defaults to `h3`
* Sote has a similarly named template under its `hdbt_subtheme`-theme in similar place to `hdbt`-theme that sets the level to `h2` and then calls the hdbt template
* A notice was added to the original theme …

UHF-3552 service channel heading level

---

templates/layout/page--401.html.twig
templates/layout/page--403.html.twig
templates/layout/page--404.html.twig
templates/layout/page.html.twig
translations/fi.po
translations/sv.po

To test:
1. Use any instance you want. Make it up to date with dev and then `composer require drupal/hdbt:dev-UHF-3864_login_block_for_403_page`
2. `make drush-cr`
3. `make shell`
4. `drush locale:check && drush locale:update && drush cr`
3. When not logged in try to access /user/1 and you should get a 403 page with login block. The layout still looks quite raw but its out of scope since there is story https://helsinkisolutionoffice.atlassian.net/browse/UHF-2879 where the layout work is done. Even tho it is a bit out of scope I added some level of styling and dom elements such as title and short description. Make sure they are all translated to English and Finnish. All Swedish translations are not here yet and since they are out of scope they also will be done in the story linked above.

UHF-3864 Login block for 403 page

---

hdbt.theme

Saving of the site settings didn't work correctly before. Fixed that so that koro, color-palette and icon are correctly saved and applied.
* Refactored the hdbt_get_settings function on hdbt.theme file.
* Get any instance running latest dev.
* `composer require drupal/hdbt_admin:dev-UHF-4064_site_settings && composer require drupal/hdbt:dev-UHF-4064_site_settings`
* `make drush-cr`
* First go to the `/admin/tools/site-settings` and select some different color-palette, koro and icon and save the page.
* Repeat the saving on all other language versions as well /fi /en /sv (not different selections - just the same you did on the first time)
* Go to the page and make sure the selections that you made are visible on the page.
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/114

UHF-4064: UHF-4064 Fix hdbt_get_settings function

---

modules/hdbt_content/hdbt_content.module

Set the autocomplete off on the high school search so that when returning to the form the inputs don't have old values and not in sync with the results listing.
* Using a form alter set the autocomplete off on the high school search paragraph form and its inputs.
* Make sure your KASKO instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-3454_autocomplete_off`
* Go to a page that has high school search or create one. 
* Select a filter and press search. 
* Switch to the map-version of the result listing.
* Click the "Open large version of the map" link.
* After you have been taken to the large version of the map press "back" on the browser.
* The form should now be in …

UHF-3454: Set high school search filters to have autocomplete off

---

templates/layout/html.html.twig

Revert attributes for the body tag.

UHF-4423: Reverted attributes for the body class.

---

hdbt.theme

* `composer require drupal/hdbt:dev-UHF-3165`
- Open any service page that contains an errand service with process_description field. For example: `/tpr-service/3622`.
- Make sure process description is shown first

UHF-3165: Reordered errand service fields inside accordion

---

.stylelintrc.yaml
package-lock.json
package.json

As part of linting discussion, we need to get SCSS linting started in the project. This is an optional conversation starter.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-3115_scss_linter`
* Run `npm install` in hdbt folder
* Add stylelint support for your editor, for example: [Stylelint for VSCode](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)
* Check that linting works

UHF-3115: Add linting for SCSS

---

templates/module/helfi-news-item/node--news-item.html.twig

* Disabled social media block for news
* `composer require drupal/hdbt:dev-UHF-X-disable-social-media-block`
* Create a News item node  and make sure it doesn't throw 5xx error anymore.

Disable social media block for news

---

templates/paragraphs/paragraph--social-media-link.html.twig

Added a check that the social media icon url exists before rendering
* `make fresh`
* Make sure you have the latest from platform config as well (configs were added in tag number 2.6.8) 
* If not run in shell `composer upgrade drupal/helfi_platform_config` and `drush updb; drush cr`
Before updating the HDBT theme, try adding the contact card listing paragraph/yhteystietokorttilistau (i.ex. to a standard page) without filling any social media links to a contact card, this should result in an error on the page when viewed.
* Run `make shell` in project root
* `composer require drupal/hdbt:dev-UHF-3504-contact-card-fix`
* `drush cr`
* The previously mentioned error should now …

UHF-3504: Added check if social media icon link renders

---

templates/paragraphs/paragraph--social-media-link.html.twig

Removed unnecessary link_attributes from social media links paragraph
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-3504-contact-card-listing-fix`
* `drush cr`

UHF-3504: Removed unnecessary link attributes

---

templates/paragraphs/paragraph--remote-video.html.twig

With current templates we get empty headings and wrong level headings in video components
* video title level is now changed based on if the component has a title
* video title is h2 for no component title
* video title is h3 for videos that have component title
* Video title heading element is removed if its contents would be empty
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_video_title_heading_fix`
* Test first without the fix
* Create a page with three video elements
* One with no video title (below video)
* Will have an empty h3 element
* One with video title (below video) and no component title (above video)
* Will have possibly …

Fix video title heading level and rendering problem

---

hdbt.theme
templates/media/media--remote-video.html.twig

Added iFrame title fields for remote video, chart and map paragraphs
* Added new mandatory fields for the three paragraphs, the fields have a default value from preprocessing before the field is filled by the content creator.
* `make fresh`
* `make shell` in project root
* `composer require drupal/helfi_platform_config:dev-UHF-4665-iframe-title-for-map`
* `composer require drupal/hdbt:dev-UHF-4665-iframe-title-for-map`
* `drush updb; drush cr;`
* Create a standard page and add a map, remote video and chart paragraphs to the page. They should now have a new field called "assistive technology title". Fill in the title and it will appear on the embedded contents iframe …

Uhf 4665 iframe title for map

---

templates/content/social-media-links.html.twig
templates/module/helfi-news-item/node--news-item.html.twig

The social media sharing block caused WSOD when enabled.
* Enable the social media block and check that necessary variables are available when trying to print the links
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-5126_social_media_wsod && composer require drupal/helfi_platform_config:dev-UHF-5126_social_media_wsod`
* Run `make drush-updb drush-cr`
* Create a news item and check that the social media links get rendered without errors
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/316

UHF-5126: Social media wsod

---

hdbt.theme

Map and chart paragraphs didn't have the media field as a mandatory field which led to an error
* Added a check to preprocessing that the media fields have content
* Add a chart paragraph to a standard page without the chart media file. This should result to an error on the page.
* Remove the chart and test the same with the map paragraph, should also lead to an error
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-4665-fix-for-chart`
* Refresh the page that has the chart paragraph without the media file. The error should now be gone.
* Test the same with the map paragraph

UHF-4665: Added check if chart, map or video field has content

---

dist/js/disable-genesys-button.min.js
hdbt.libraries.yml
hdbt.theme
src/js/disable-genesys-button.js
translations/fi.po
translations/sv.po

Disabling (or more precisely, not displaying) the button that opens the chat when the Genesys chat element does not exist on the page.
* Added a JavaScript library that checks the existence of the Genesys chat element and replaces the button with a more informative text if it does not exist
* Set up STRATEGIA instance with `make fresh`
* Get this branch of the HDBT theme: `composer require drupal/hdbt:dev-UHF-5228_disable_genesys_button`
* Get the equivalent branch of the Platform Config module: `composer require drupal/helfi_platform_config:dev-UHF-5228_disable_genesys_button`
* Enter the container: `make shell`
* Update the translations: `drush locale:check && drush locale:update && drush cr`
* Navigate to https://strategia.docker.so/fi/paatoksenteko-ja-hallinto/tuki-ja-neuvonta/helsinki …

UHF-5228: disable genesys button

---

modules/hdbt_global_navigation/hdbt_global_navigation.info.yml

Added new empty module inside hdbt/modules to provide a place for adding global navigation theming
(Inside hdbt directory)
- `git fetch`
- `git co origin/UHF-X-global-navigation-base ` 
- `drush cr`
- `drush en hdbt_global_navigation`

UHF-X Add new empty base module for global navigation theming.

---

.stylelintrc.yaml
package-lock.json
package.json

Our stylelint did not explain the decisions nor check for color values.
* Improved stylelint configuration
* Added checks for low performance animation properties
* Added checks for invalid `overflow: none``
* Added checks for ignored properties
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_improve_stylelint`

UHF-X: Improve stylelint messaging and warn about direct color values

---

templates/block/block--system-branding-block.html.twig
templates/layout/region--footer-bottom.html.twig
templates/misc/logo.twig

* The title attribute in logos is read poorly in screen readers and are only visible on devices with a pointer.
* The Helsinki logo is read out loud as "Helsinki", which is wrong, it's the logo of Helsinki or Helsinki city.
* Title attribute removed
* Helsinki logo was properly named according to [this chat](https://helsinkicity.slack.com/archives/G01EWJJVAUW/p1655821233137499?thread_ts=1655705554.640059&cid=G01EWJJVAUW).
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_improve_logo_a11y`

UHF-X improve logo accessibility

---

translations/fi.po

Finnish translation does not match the english key due to an extra period.
* Period was removed from both Finnish translation and the Finnish version of the key
* Check a 404 page in Finnish first to see if it has text in English in your instance
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_404_translation_error`
* Run `make shell`
* Run in shell `drush locale:check && drush locale:update`
* Run `Flush all caches` in drupal admin teardrop-menu

UHF-X: Fix translation bug

---

src/js/nav-global.js

Cache the mobile menu request to local storage, eliminating the need to make the same request in succession.
Added logic to cache the mobile menu request into localstorage. Added timestamp to act as a cache invalidator. 
Mobile menu is still a work in progress. To test this issue, some tricks are needed:
* Get the feature branch from platfom config: `composer require drupal/helfi_platform_config:dev-UHF-6038-menu-data-syncing`
* Enable global menu feature: `drush en helfi_navigation -y`
* (Get this branch: `composer require drupal/hdbt:dev-UHF-6198-mobile-menu-caching)` Change line 260 of `themes/contrib/hdbt/src/js/nav-global.js` to `const MENU = mockmenu;`
* Pull the branch `UHF-6038-menu-data-syncing` into your local HDBT. This commit adds some templates - pulling it will prevents the …

UHF-6198: Cache mobilemenu response to localstorage

---

config/install/block.block.hdbt_page_title.yml
config/install/block.block.heroblock.yml
config/install/block.block.main_navigation_level_2.yml
config/install/block.block.sidebarcontentblock.yml

* Removed ctools dependencies from hdbt install config.
* Check site specific PR's for testing instructions.
* Related module PR:
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/352
* Site specific PRs:
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/435
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/419
* https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/308
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/204
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/95
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/43
* https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull/114
* https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/113

UHF-6300: Remove ctools dependencies from hdbt install config

---

package-lock.json
package.json

* Updated SVG-Sprite node module to keep up with the changes
* Fixed vulnerabilities from other node modules
* Get this branch `UHF-X_svg_sprite_v2` and run `nvm use && npm i && npm run build`

Updated SVG-Sprite node module to 2.0.0 beta7 and fixed vulnerabilities.

---

templates/block/block--external-menu-block-fallback.html.twig
templates/block/block--mobile-navigation.html.twig

Fixes a problem found in 14.9 accessibility checks that some screen readers on some browsers do not read the help text from aria-label elements that do not have a role. This moves the text out from aria-label attribute into the actual content and hides it from non-screen readers while hiding the shown text from screen readers with aria-hidden.
This code was discussed and should be the one we aim for:
* Global and local menu were fixed by moving the help text outside from aria-label to actual page content.
* `make fresh`

UHF-6727: Fix menu button help text for some screen readers

---

hdbt.theme

* [Added fix for the missing lang attribute in main menus.](https://github.com/City-of-Helsinki/drupal-hdbt/commit/67e7779e2addeb150c8bc57edb5ecb7ace0a15b6)
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_lang_attribute_fix`

UHF-X Lang attribute fix

---

templates/layout/page.html.twig

* Changes otherlangs button and block check to if global navigation is enabled
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X-otherlangs-fix`

Changes other langscheck to if global nav is enabled

---

templates/navigation/menu.html.twig

Removed dropdown button when there is no children.
* Removed dropdown button when there is no children.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-6829-dropdown-indicator-fix`

UHF-6829: Removed dropdown button when there is no children.

---

templates/navigation/menu.html.twig

Language attribute was leaking to parent li-element, thus causing the possible screen reader help texts to be in wrong lang.
* li-element no longer has lang-attribute
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_lang_attribute_leak`

Remove lang attribute from li-element in menu

---

templates/block/block--external-menu-block--header-top-navigation.html.twig
templates/layout/region--header-top.html.twig
translations/fi.po
translations/sv.po

Header top nav (the one with the coronavirus link) does not have an translated and a reasonable name.
* A name was added to the top nav
* To add the name, a new template was created
* The h2 title was moved to aria-label to keep the headings clear from above h1 heading
* Translations were added
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7024_header_top_a11y_name`
* Update translations and empty your cache (from the drupal teardrop)

UHF-7024: Add translated description to header top bar nav for screenreaders

---

templates/layout/page.html.twig

Header search does not play nicely when global nav is disabled.
* Header search was removed from html source when global nav is disabled (js was already disabled)
* `make fresh`
* Disable global nav from your instance `drush pm-uninstall helfi_navigation` (you can later re-enable it with `drush en helfi_navigation`)
* `composer require drupal/hdbt:dev-UHF-X_hide_local_nav_header_search`

Hide header search when global nav is disabled

---

templates/block/block--chatleijuke.html.twig

* Added template for the chat leijuke block to prevent printing of the block title.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_chat_leijuke_fix`

UHF-X Chat leijuke fix

---

hdbt.theme
templates/layout/region--footer-bottom.html.twig

* Replaced logo links to point to Etusivu-instance.
* `make fresh`
* Update the HDBT theme and necessary modules
* `composer require drupal/hdbt:dev-UHF-6960_front_page_tasks`
* `composer require drupal/helfi_platform_config:dev-UHF-6960_front_page_tasks`
* `composer require drupal/helfi_navigation:dev-UHF-6960_front_page_tasks`
* `composer update drupal/helfi_api_base -W` 
* Check that the following links point to Etusivu -instance (helfi-etusivu.docker.so)
* The mobile menu and mobile menu fallback "Front page" -link 
* The header logo and footer bottom logo -links
* The breadcrumb "Front page" link
* Check that the code follows our coding standards 
* …

UHF-6960: Front page tasks

---

templates/block/block--external-menu-block-fallback.html.twig

* Changed header top navigation to variable, instead of twig block
* Make sure your "Etusivu" instance is up and running on latest `UHF-6960_front_page_quicklinks` branch.
* `git pull origin UHF-6960_front_page_quicklinks`
* `composer require drupal/hdbt:dev-UHF-6960_front_page_quicklinks`
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/179

UHF-6960 Front page quicklinks

---

templates/module/helfi-news-item/node--news-item.html.twig
translations/fi.po
translations/sv.po

* Added missing "Published over a year ago" tag for news item
Test in etusivu intance
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-6983-news-published-year-ago-tag`

UHF-6983: Added published over a year ago tag for news item

---

modules/hdbt_content/hdbt_content.tokens.inc

* Fixed an error when job listing's organization field was empty.
* Make sure your `rekry` instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7253-fix-missing-organization-error`
* Before using this branch, you can try to replicate the error.
* Edit some job listing and remove the organization reference.
* You should get error when viewing the job listing after saving.
* Change to this branch and reload the page. The job listing page should work as expected.

UHF-7253: Fix error when organization entity is missing

---

config/install/block.block.footertopnavigationsecond.yml
config/install/language/fi/block.block.footertopnavigationsecond.yml
config/install/language/sv/block.block.footertopnavigationsecond.yml
config/install/system.menu.footer-top-navigation-2.yml
modules/hdbt_content/hdbt_content.install

Remove footer top content configuration and replace it with a real menu on instances that don't use global navigation.
* Check if there is footer top content block set and remove it.
* Add new menu called footer top navigation - second.
* Add new menu block to footer that displays the new footer top navigation - second menu contents.
* Check instructions from the [hdbt_admin PR](https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/173)
* Check instructions from the [hdbt_admin PR](https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/173)
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/173
* https://github.com/City-of-Helsinki/drupal-module-helfi-navigation/pull/19

UHF-7139: Remove footer top content configuration

---

modules/hdbt_content/hdbt_content.tokens.inc

* `composer require drupal/hdbt:dev-UHF-7126`

UHF-7126: Run token url through file generator

---

templates/module/helfi_tpr/tpr-content-liftup.html.twig

At the moment `drush twig:compile` fails with the following error:

Fixed twig:compile error

---

templates/paragraphs/paragraph--news-list.html.twig
translations/fi.po
translations/sv.po

News listing produces an empty ul-element when there are no news to list. It looks confusing, ugly and causes siteimprove to lose its marbles. 😕 
* An error message `<p>` was added instead of the `<ul>` element when there are no news.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-UHF-7685_no_news`
* This PR does not need designers review
[UHF-7685]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7685: Show message when newslist has now news to list

---

templates/module/helfi_tpr/tpr-unit--wide-teaser.html.twig

TPR-unit wide teaser has heading level `<h3>` even when it's it's on [a page with no `<h2>` on it](https://www.hel.fi/en/decision-making/contact-us/helsinki-info/helsinki-infos-contact-information).
* Heading level was set to H2
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_tpr_unit_wide_teaser_heading_level`
* This PR does not need designers review

UHF-X: Fix TPR-unit wide teaser heading level

---

hdbt.theme

Editors can accidentally cause skipping in heading levels from [h2 to h4 for example](https://www.hel.fi/fi/sosiaali-ja-terveyspalvelut/toihin-meille/opiskelijalle-ja-harjoittelijalle#fysioterapian-ja-toimintaterapian-opiskelijat).  This causes screen readers problems and Siteimprove complains about it.
* If accordion paragraph contains a title and the heading level skips numbers between accordion title level and accordion item title levels, use accordion title level +1 as accordion item title level. (in our title h2, item h4 example, item level becomes h3)
* While we could fix item level being lower than title level, it's perfectly valid for screen readers and siteimprove, so lets not try to be too smart in case someone actually needs the functionality.
* Make sure your instance is up …

UHF-X: Fix skipping in accordion heading levels

---

templates/module/helfi_tpr/tpr-service-channel.html.twig
translations/fi.po
translations/sv.po

One text copy was missing a translation for Finnish and Swedish in the service channel component.
* Added the translations for "call charge".
* Make sure your asuminen instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7343_Service-channel-translations`
* Run `drush locale:check && drush locale:update`
[UHF-7343]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7343: Added missing translations for the service channel

---

hdbt.libraries.yml

Event list library was removed inadvertently when fixing conflicts :( This PR adds it back.
If you need to test more check instruction from this PR:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/508

UHF-X: add event list library back that was removed my mistake.

---

hdbt.theme

Fix related to [UHF-8070](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8070) changes.
* Add better location field value check. Location field was recently added to events paragraph. If node hasn't been saved after that boolean field value doesn't exist.
* Make sure SOTE instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X-location-field-value-check`
- https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/senioripalvelut/palvelukeskukset/musiikkiryhmat-palvelukeskuksessa
- https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/senioripalvelut/palvelukeskukset
- https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/senioripalvelut/palvelukesku …

UHF-X: add better location field value check

---

templates/component/accordion.twig
templates/misc/nav-toggle-button.twig
templates/navigation/menu--external-header-language-links.html.twig
templates/navigation/menu--external-menu--fallback.html.twig
templates/navigation/menu--external-menu--mega-menu.html.twig
templates/navigation/menu--mobile.html.twig
templates/navigation/menu.html.twig
templates/navigation/pager.html.twig

Siteimprove was complaining about duplicate ids on a page: https://www.hel.fi/fi/paatoksenteko-ja-hallinto/sisallonhallinta/sivujen-rakentaminen-drupalissa/sivupohjat-ja-niiden-valinta/perussivu/esimerkki
It turned out that we had a id that leaked its contents as it did not have quotes arounds its empty value.
* Checked for other such problems and found potential problems in multiple places.
* The places where attributes were set without quotes were fixed in this PR 
* The id did not have contents because the variable was misnamed, this was fixed
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_fix_html_attributes_missing_quotes`

UHF-X: Add missing quotes around html attribute values

---

hdbt.theme
templates/module/helfi_tpr/field--service-map-embed.html.twig

The cookie content blocker didn't work on TPR unit pages.
* Use the cookie content blocker template also on TPR unit maps.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-5047_TPR-unit-map-cookies`
[UHF-5047]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-5047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-5047: Cookie content blocker on TPR unit maps

---

hdbt.theme

In the image caption, the photographer text is taken from the default language even though there is a translation available. Example of the issue: https://www.hel.fi/fi/uutiset/pormestari-vartiainen-tapasi-new-yorkin-pormestarin-ja-osallistuu-yhdysvaltojen.
* If it exists, get the translated photographer value.
* `composer require drupal/hdbt:dev-UHF-7960_Photographer-info-wrong-translation`
[UHF-7960]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7960: Get translated value for photographer if it exists

---

hdbt.theme

In the image caption, the photographer text is taken from the default language even though there is a translation available. Example of the issue: https://www.hel.fi/fi/uutiset/pormestari-vartiainen-tapasi-new-yorkin-pormestarin-ja-osallistuu-yhdysvaltojen.
* If it exists, get the translated photographer value.
* `composer require drupal/hdbt:dev-UHF-7960_Photographer-info-wrong-translation`
[UHF-7960]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/572

UHF-7960: Get translated value for photographer if it exists.

---

templates/navigation/menu.html.twig

As WAI-ARIA spec has changed to limit the usage of this attribute only to role="menu", we got recommendation from Siteimprove Tero P to stop using this previously recommended practise.
Check #dev-helfi-hds channel in slack for [more info](https://helsinkicity.slack.com/archives/C0370RQ48CR/p1678952230417919).
* The `aria-haspopup` attribute was removed as recommended by experts
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_remove_aria_haspopup`

UHF-X: Remove aria-haspopup from dropdown menu

---

templates/views/views-view--unit-search.html.twig
translations/fi.po
translations/sv.po

The title over the results in the Private general upper secondary school search [on this page](https://helfi-kasko.docker.so/en/childhood-and-education/general-upper-secondary-education/general-upper-secondary-schools) says just " results" with a small "r" if there are no results.
* Removed the "x results" when there are no results.
* Make sure your Kasko instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-x_Unit-search-no-results-title`
* Run `make shell` and then `drush locale:check && drush locale:update`

UHF-X: Results title in unit search with 0 results

---

src/scss/06_components/paragraphs/_list-of-links.scss

* Added logical properties support for Link List paragraph
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8225-Link_list_paragraph_language_support`
[UHF-8225]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8225: Logical properties support for Link List paragraph

---

hdbt.theme

Content was shown based on interface language instead of content language
Changed getCurrentLanguage method to fetch content language instead of interface language
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8090_ui_lang_fix`
Check the etusivu-pr
The etusivu 8090 pr
[UHF-8090]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8090 UI lang fix

---

src/scss/05_objects/_link.scss

* Added RTL language support for Popular Services paragraph
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8226_Popular_services_paragraph_language_support`
[UHF-8226]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8226: Popular services language support

---

hdbt.theme
src/scss/06_components/pages/_cookie-compliance.scss
templates/media/media--hel-map.html.twig
templates/misc/embedded-content-cookie-compliance.twig
templates/module/helfi_api_base/helfi-link.html.twig
templates/module/helfi_tpr/field--service-map-embed.html.twig

The embedded content blocker doesn't need to support RTL languages as it's displayed in English.
* Reverted the added RTL support
* Wrapper the embedded content cookie blocker screen `dir` and `lang` attributes.
* Added `primary_languages` variable to be available in all templates.
* Added `dir` and `lang` attributes and switched `aria-label` to `aria-labelledby` in the external link, telephone and email fields (part of [UHF-8089](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8089)).
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-0000_embedded_content-cookie-blocker-lang-fixes`
* Run `npm run build` inside hdbt theme.
[UHF-8089]: …

UHF-0000 embedded content cookie blocker lang fixes

---

hdbt.theme

_hdbt_set_site_information is called in hdbt_preprocess_region and hdbt_preprocess_block. Must use TYPE_CONTENT as parameter

UHF-8290 getCurrentLanguage parameters

---

hdbt.theme
templates/paragraphs/paragraph--calculator.html.twig

* Fixed calculators not working with proxy.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7568_fix_theme_path_issue`
[UHF-7568]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7568 fix theme path issue

---

src/js/nav-global/menu.js
templates/layout/html.html.twig

aria-label should be changed to aria-labelledby.
* Changed to use aria-labelledby in the mobile menu
* Added hidden spans with labels to the top of the page for external, tel and mailto links. Now they can be used wherever needed, for example in the mobile menu.
* Some other existing "Link leads to external service" spans are not touched yet in this since they are being edited same time in another branch.
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8089_Mobile-menu-external-link-aria-labels`
This needs to be merged first: https://github.com/City-of-Helsinki/drupal-hdbt/pull/588.
[UHF-8089]: …

UHF-8089 Switch aria-label to aria-labelledby in mobile menu

---

hdbt.theme
templates/content/node--announcement--default.html.twig
templates/misc/status-messages.html.twig

Some accessibiity work for announcement and status message components
* Add preprocess hook too expose accessibility-related variables to announcements template
* Implement accessibiity fixes to announcement and status message templates
* Boot up an instance of your choice
* Get this branch. `composer require drupal/hdbt:dev-UHF-7853-notification-components-accessibility` 
* Create 3 instances of announcements (/node/add/announcement) and select a different type for each of them. Make sure that all have "Show on all pages" option checked.
* After you save the last of them, Drupal should redirect you to the announcement's node page. On this page you should see:
* All the announcements you created
* Drupal's status message informing you that that you have just published an announcement …

UHF-7853: Notification components accessibility

---

templates/misc/tag-list.twig
templates/paragraphs/paragraph--news-list.html.twig

Fix missing class from news list paragraph
[UHF-8215]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8215: Add tag container class to news list paragraph

---

templates/layout/maintenance-page.html.twig

* Temporarily added hardcoded URL for the maintenance mode page illustration as the azure assets path do not work for maintenance page.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_maintenance_mode_image`

UHF-X Maintenance mode image

---

templates/content/node--announcement--default.html.twig

* Added doublequotes to aria-label
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7853_announcement_quotes`
[UHF-7853]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7853: Announcement quotes

---

dist/js/hyphenopoly_settings.min.js
hdbt.libraries.yml

* Changed hyphenopoly library js-files to preprocess false value.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-7113_hyphenopoly_fixes`
* We need to test that the hyphenopoly works with Drupal JS aggregation turned on so we need to do the following:
* Make sure that you have the aggregation turned on. Comment these lines from local.settings.php file if they are not already:
* `$config['system.performance']['css']['preprocess'] = 0;`
* `$config['system.performance']['js']['preprocess'] = 0;`
* Edit the `hyphenopoly_settings.js` file and change the `'fi'` value to `FORCEHYPHENOPOLY`.
* Compile the theme styles `nvm use && npm i && npm run build`
* …

UHF-7113 Hyphenopoly preprocess false

---

package-lock.json
package.json

* Added preinstall for package.json that checks if there is updates for browserslist db
* Make sure your instance is up and running on latest dev branch. 
* `composer require drupal/hdbt:dev-UHF-7006_browserslist_db_automatic_update`
* Go under the hdbt theme and run `nvm use && npm i && npm run build`
* The theme compiling should now say at some point:
```
> hdbt_subtheme@1.0.0 preinstall
> npx browserslist@latest --update-db
```
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/659
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/129
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/360
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/371
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/638
* …

UHF-7006: Browserslist db automatic update

---

templates/module/helfi-news-item/node--news-item.html.twig

* Fixed typo on news page tag listing element that prevented news tags being rendered
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_news_tags_not_displaying_correctly_in_news_page`

UHF-X: Fixed typo on news page tag listing element that prevented news tags being rendered

---

src/scss/06_components/pages/_service-channel.scss
src/scss/06_components/pages/_unit.scss
src/scss/06_components/paragraphs/_content-liftup.scss
src/scss/06_components/paragraphs/_map.scss
templates/misc/address-plain.html.twig
templates/misc/tag-list.twig
templates/module/helfi_tpr/field--tpr-service-channel--address.html.twig

TPR Unit listing was missing comma separator on the address info
* Added commas to all possible places in address twig
* Removed commas from CSS that were causing double comma
* Hide commas from places where they're not supposed to be used (when the address is multiline)
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8431_Fix_missing_comma`
(e.g. `/fi/kasvatus-ja-koulutus/varhaiskasvatus/varhaiskasvatus-paivakodissa/etsi-kunnallisia-paivakoteja`)
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/582
[UHF-8431]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

UHF-8431: Missing comma separator on address

---

hdbt.theme

* `composer require drupal/hdbt:dev-UHF-8443`
[UHF-8443]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8443: Make sure image entity is loaded in correct language

---

templates/media/media--hel-map.html.twig

The map component twig template is using wrong version of the map URL.
* Fixed the template to use correct URL variable, which is provided by code that makes sure that the map URL gets the `/embed` to the URL.
* Make sure your Kasko instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8519_map-embed-url-fix`
[UHF-8519]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8519: Fixed the map embed URL.

---

translations/fi.po
translations/sv.po

* Changed translation for sentence "Close menu" to "Open menu" for FI and SV languages. As it is originally on source language.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8485_Translation_fix`
[UHF-8485]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8485: Fix translation for profile menu accessibility

---

hdbt.theme
templates/media/media--hel-map.html.twig
templates/media/media--remote-video.html.twig
templates/misc/embedded-content-cookie-compliance.twig

* Added iframe title field value to variables so that media map templates can use it.
* Passed it for embedded content cookie compliance template and added a separate label for screen readers to read when on the "See content on external site" link.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8465_see_content_on_external_site_link_accessibility`
[UHF-8465]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8465: Changed the See content on external site links to include the iframe title for screen readers

---

templates/module/helfi_tpr/tpr-unit.html.twig

Some fields from TPR were missing from unit pages.
* Added missing fields to the unit template.
* Check the other PR for instructions: https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/147
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/147
[UHF-8595]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8595: Added missing TPR fields

---

templates/navigation/menu-local-tasks.html.twig

* The login page starts with a h2-element because the local tasks block has an h2 title. This title is not very useful for the user browsing the page with a screenreader that it is meant for so we should just remove it.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8586_remove_local_tasks_block_title`
[UHF-8586]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8586: Remove menu local tasks block title

---

templates/module/helfi-news-item/news-teaser-generic.twig

* News items in news block were shown with unpublished styles even tho they were published. 
* Make sure your instance is up and running on latest dev branch. For example KASKO is good for testing this but any will do except for front page.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8759_fix_for_external_entities_appearing_unpublished`
[UHF-8759]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8759: Add check for news-teaser-generic if the entity is node before checking for the published state

---

templates/module/helfi_api_base/helfi-link.html.twig

Adding a comment to helfi_link twig that with this change https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/119
The twig template is no longer called for all links, but only for few  - currently the external links + buttons (with icons including) 
This change was done because of performance considerations
[PLATTA-4940]: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLATTA-4940

---

templates/field/field--tpr-service-channel--availability-summary.html.twig

* Added field template for availability summary field on service channel to remove wrapping <p>-tag since the content is always just one paragraph.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8786_service_channel_availability_summary_layout_bug`
[UHF-8786]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8786: Availability summary bug fix

---

dist/js/disable-genesys-button.min.js
package-lock.json
src/js/disable-genesys-button.js

Make button on helsinki info pages usable again.
* Added ID to genesys-disabled message to make it replaceable from the neuvonta chat script. Neuvonta script loads genesys from external source and seems that global `_genesys` object is never available when the `disable-genesys-button` script executes.
* Updated `caniuse-lite`
* Check instructions here: 
[UHF-7650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-7650: Fix helsinki info button

---

README.md

Make commands for compiling the theme were already documented in [City-of-Helsinki/drupal-helfi-platform](https://github.com/City-of-Helsinki/drupal-helfi-platform/blob/main/documentation/build-assets.md) repository. This PR adds description of the commands to this repository so they are easier to find.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8510-document-theme-build-commands`
* City-of-Helsinki/drupal-helfi-platform#131
[UHF-8510]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8510: Document commands for building assets in containers

---

templates/component/accordion.twig
templates/misc/component.twig

* Part of accordion close button's screen reader text didn't have fallback lang attribute.
* Latest news component title doesn't have lang attribute.
* Added missing lang fallback attributes.
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8707_other-languages-bugs`
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/420)
[UHF-8707]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8707 other languages bugs

---

hdbt.theme
templates/module/helfi_tpr/tpr-unit.html.twig

* Add field unit picture caption and make it function the same way as other caption fields.
* `make fresh`
* `make drush-cim drush-cr`
* `composer require drupal/hdbt:dev-UHF-8938`
* Update the helfi_platform_config
* `composer require drupal/helfi_platform_config:dev-UHF-8938`
* Run `make drush-updb drush-cr`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/606
[UHF-8938]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8938: Caption field for TPR-units

---

templates/paragraphs/paragraph--hearings.html.twig

open the link in same window
removed target=blank
* `make fresh`
- Go to any landing page and add a hearings paragraph to it
- Go see the paragraph.
The "see all hearings(katso kaikki kuulemiset)" link should open in same tab instead of opening a new tab 
[UHF-9178]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9178: open the link in same window

---

templates/module/helfi_tpr/tpr-service.html.twig

Image paragraph on TPR Service page was not displayed if image didn't have caption text.
* Updated rendering filters for conditional statement for Upper Content region.
* Recommendation of using https://github.com/City-of-Helsinki/drupal-helfi-sote
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9068_Image_not_visible`
[UHF-9068]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9068: Fix visibility of image without caption

---

backstop_data/backstop_dynamic_config.js

The visual regression tests failed even though nothing had really changed.
* Removed the iframes, since it doesn't make sense to test external content.
* Fixed the selector of announcements.
* Tweaked the testing of the `text` component, earlier only the first heading was tested and it wasn't so useful in my opinion.
* Make sure your platform test instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9126_fix-false-positives`
Run these commands inside the HDBT theme root.
* Run `npm run fast-reference`
* Run `npm run fast-test`
* Check the results at https://platform-test.docker.so/themes/contrib/hdbt/backstop_data/fast/html_report/index.html
**Note:** There is a problem …

UHF-9126 fix false positives

---

templates/module/helfi_tpr/tpr-service-channel.html.twig

We have empty headings in a minor amount of content
* A check was added to avoid creating empty headings
* `make fresh` on kymp instance
* `composer require drupal/hdbt:dev-UHF-X_service_channel_empty_title`

UHF-X: Hide empty title from service channel TPR content

---

templates/module/helfi_tpr/tpr-unit.html.twig

Other info accordion is displayed on TPR units even if it doesn't have any content.
Example: https://www.hel.fi/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/sairaalat-ja-poliklinikat/laakson-sairaala.
* Moved the accordion rendering to be inside the if statement.
* Fixed indenting.
* Make sure your **SOTE** instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9298_other-info-accordion-bug`
[UHF-9298]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9298: Fixed other info accordion bug in tpr units

---

templates/layout/region--tools.html.twig

On many pages (6k+) we have empty `tools__container` element from drupal as the check did not work in all cases.
* twig if was improved by adding `|render`
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_tools__container`

UHF-X: Improve check for tools__container content

---

hdbt.theme
templates/module/helfi_tpr/tpr-unit.html.twig
translations/fi.po
translations/sv.po

* Display subgroups in an accordion
* Follow the instuctions in https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/161.
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/161
[UHF-9159]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9159: Added subgroup accordion

---

hdbt.theme
templates/layout/maintenance-page.html.twig
translations/fi.po
translations/sv.po

* Added a link leading to the copy of the site to the maintenance page.
* Make sure your **etusivu** instance is up and running on latest dev branch.
* `make fresh`
* Run `make drush-locale-update drush-cr`
* Run `drush state:set system.maintenance_mode 1 --input-format=integer` to put the site to the maintenance mode.
[UHF-9309]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9309 link to static copy of the site

---

templates/module/helfi_api_base/helfi-link.html.twig

* Fixed empty space issue on helfi-link template with email/phone icons.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_fix_for_helfi_link_icons`
* Check the test instance for reference https://www.hel.fi/fi/test-kasvatus-ja-koulutus/perusopetus/kouluun-ilmoittautuminen-ja-hakeminen/painotettu-opetus-ja-perusopetusta-eri-kielilla/englanninkielinen-opetus

UHF-X Fix for helfi link icons

---

backstop_data/backstop_dynamic_config.js

* Removed TPR unit with sidebar configurations as those do not exist.
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/665
[UHF-9215]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9215: TPR Unit test content

---

templates/module/helfi_tpr/tpr-unit.html.twig

* Use the description override if the TPR data for description is empty.
* Check the instructions in https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/653
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/653
[UHF-9249]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9249: Use the new description override field

---

templates/module/helfi_tpr/tpr-service--teaser-search-result.html.twig

Advisory services listing has invalid `p > p` structure as the card component is called as if the description would not have html formatting. 
This causes the browser to create empty p-tags before and after the description content.
* tpr-service--teaser-search-result.html.twig was modified to tell the card template that the card_description format is indeed html.
* Make sure your *Strategia* instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_advisory_services_teaser_html`

UHF-X: Fix nested p-tags in tpr-service-teaser description

---

templates/module/helfi_tpr/tpr-unit--minimal.html.twig

Remove unnecessary '-' from after-school activity card.
The field is a text-field in TPR, so formatting it on Drupal side is a bit fragile. However, with this simple change, the result looks better with current field values.
* Make sure your KASKO is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9230-after-school-activity-search-card`
* #884
[UHF-9230]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9230: Remove unnecessary "-" from after school activity card

---

hdbt.theme
templates/form/form-element-label--unit-search.html.twig
templates/form/text-input/form-element--textfield--unit-search.html.twig
translations/fi.po
translations/sv.po

* Add theme suggestions and templates for the Unit Search paragraph so that the default content can be printed to the form items in the code.
* Check installation instructions from the [platform_config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/686).
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/686
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/906
[UHF-9311]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9311: Unit search paragraph changes and improvements

---

hdbt.theme

We currently have no visibility to actual alt attributes.
* This adds original alt to `data-alt-original` attribute so that we can debug it.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_get_original_alt`

UHF-X: Add original alt attribute to all images

---

hdbt.theme

`total_rows` was not defined if `$variables['view']->total_rows` is zero, since `0 == NULL` evaluates to true. This patch ensures that total rows is always defined so templates can use it without checking.
Find a view with zero results *OR* find a view and delete its result nodes. Following code triggers the issue:
```twig
{% plural total_rows %}
```
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9566`
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/388
* previous attempt to fix the issue. However, this is a better solution, since it applies to all templates, not just rekry.
[UHF-9566]: …

UHF-9566: Fix deprecated call abs(): Passing null to parameter #1

---

templates/module/helfi_tpr/tpr-service-channel.html.twig

* Print the information field on service channel if it has content.
* Check installation instructions from the [TPR PR](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/168)
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/703
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/915
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/168
[UHF-9440]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9440: Print information field for the service channel card if there is any

---

templates/module/helfi_tpr/tpr-unit-contact-information.html.twig

* Add mailto formatter to tpr unit email field.
* `make fresh`
* Update the HDBT theme & platform config
* `composer require drupal/hdbt:dev-UHF-9562-unit-email-field`
* `composer require drupal/helfi_platform_config:dev-UHF-9562-unit-email-field`
* Run `make drush-cr drush-updb`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/722
[UHF-9562]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9562: Add email to template

---

package-lock.json
templates/module/helfi_tpr/tpr-errand-service.html.twig

The links are not appearing without also defining extra information text.
For example [this Kymp page](https://www.hel.fi/fi/kaupunkiymparisto-ja-liikenne/pysakointi/yrityspysakointi) has links in [Finnish](https://www.hel.fi/fi/kaupunkiymparisto-ja-liikenne/pysakointi/yrityspysakointi) and [Swedish](https://www.hel.fi/sv/stadsmiljo-och-trafik/parkering/foretagsparkering), but only Finnish has extra information text and only that accordion is visible:
* The twig template if-statement was modified to check the actual content of the accordion, thus making the links visible even without the extra information text.
* Make sure your instance (KYMP) is up and running on latest dev branch.
* `make fresh`
* `composer require …

UHF-9786: Fix missing links

---

src/js/hds-cc/hds-cc.js
src/js/hds-cc/template.js
src/scss/cookie-consent.scss
templates/misc/cookie-container.html.twig

The cookie banner should be able to render itself on a standard page instead of as a banner when conditions are met.
* Cookie banner functionality was extended to support the page rendering
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9797_standalone_cookie_page`
[UHF-9797]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9797 standalone cookie page

---

src/js/react/apps/job-search/containers/SearchMonitorContainer.tsx

In test/prod, url for hakuvahti endpoint needs full prefixed path, but on local it does not. 
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-x_fix_test_env`

Test/prod environment needs full path for this url. Fix.

---

templates/layout/page--system--401.html.twig
templates/layout/page--system--403.html.twig
templates/layout/page--system--404.html.twig
templates/navigation/links--language-block.html.twig

* This PR adds templates for the system error pages 401, 403 and 404. They are already correctly displayed in the case of a real error but these pages in the path /system/[error-number] can in some cases be seen by users and in those situations the layout is broken.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10060`
* Update the helfi_platform_config
* `composer require drupal/helfi_platform_config:dev-UHF-10060` 
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1005
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/771
[UHF-10060]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10060?atlOrigin=eyJpIjoiNWRkNT …

UHF-10060: Fix system error pages

---

hdbt.libraries.yml

Bump job search libraries version for cache clear.
* `make fresh`

UHF-10101: Bump job search library version, new js isnt loading at test

---

templates/navigation/links--language-block.html.twig

* Hide the alternative languages on the language switcher even if they are active
* Make sure your front page instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10201`
[UHF-10201]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10201: Hide the alternative languages on the language switcher even if they are active

---

hdbt.libraries.yml

* Update the news archive library to 1.3 so that the old version is removed from cache
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9741_update_news_archive_library`
[UHF-9741]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9741: Update the news archive library to 1.3 so that the old version is removed from cache

---

hdbt.theme

* Fixed feedback links to point to correct place
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_fix_404_feedback_link`

UHF-X: Changed the feedback link to point to correct place

---

templates/module/helfi-news-item/views-view--news-archive.html.twig
templates/paragraphs/paragraph--news-archive.html.twig

* Change news archive fallback and rss views to use drupal database instead of elastic index to make the rss filtering work correctly
* Check installation instructions from the front page instance PR: https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/683
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1043
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/683
[UHF-10469]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10469: Revert news archive from index to database based

---

hdbt.theme

Päätökset triggers hdbt_preprocess_feed_icon such that `title` is not in match statement. This throws an exception.

UHF-10424: Fix match statement in hdbt_preprocess_feed_icon

---

hdbt.libraries.yml

* Added minified: true, to fix the issue with delivering non-aggregated JS files. See: https://www.drupal.org/project/drupal/issues/3416508
[UHF-10547]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10547 Preprocessing JS files

---

hdbt.libraries.yml

* Js libraries are broken in [etusivu test](https://www.test.hel.ninja/fi) for anonymous users. I believe this should fix the issue.
Core [moves dependencies of header library to header](https://github.com/drupal/drupal/blob/10.3.x/core/lib/Drupal/Core/Asset/AssetResolver.php#L281-L284). However, this does not appear to happen to other way, dependencies of footer libraries are not moved to footer. [JsAssetController](https://github.com/drupal/drupal/blob/10.3.x/core/modules/system/src/Controller/JsAssetController.php#L53-L57) loads only the libraries in current scope (header or footer). If some dependencies are missing, the asset hashes do not match, and the asset [controller triggers a redirect response](https://github.com/drupal/drupal/blob/10.3.x/core/modules/system/src/Controller/Asset …

Footer Js libraries should not have dependencies to header libraries

---

templates/media/media--hel-map.html.twig

Prevents fatal errors on normal content pages if map media entity has erroneous URL.
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/813
[UHF-10404]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10404: Prevent fatal errors when rendering broken map entities

---

templates/misc/tag-list.twig

* Siteimprove [found bunch of broken](https://my2.siteimprove.com/Accessibility/398510/50178268819/NextGen/Issue/1?query=/fi/&conformance=&pageSegments=&ruleName=sia-r110&ruleId=110&issueKind=1&exceptTags=1,2&siteTarget.conformanceLevels=0,1,3,4) `role=&nbsp;group&nbsp;`-attributes due to twig parsing in Sote and Rekry instances
* Syntax was fixed
* Make sure your Rekry or Sote instance is up and running on latest dev branch.
* `make fresh`

UHF-X: Fix tag-list.twig role group quotes

---

templates/module/helfi-news-item/node--news-item.html.twig

* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/718

UHF-10745: Hide article timestamp

---

templates/module/helfi_platform_config/react-and-share.html.twig
translations/fi.po
translations/sv.po

* Changed the texts that are displayed on the Askem block when cookies are not allowed by the user.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8833`
* Run `make drush-locale-update drush-cr`
FI
Haluatko antaa meille palautetta tästä sivusta?
Pääset antamaan palautetta, jos sallit evästeasetuksista tilastointiin liittyvät evästeet.
SV
Vill du ge oss feedback om denna sida?
Du kan ge oss feedback genom att aktivera statistikrelaterade cookies.
EN
Would you like to give feedback on this page?
Enabling cookies that collect statistics will allow you to share your input.
[UHF-8833]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8833?atlOrigin=eyJpIjoiNWRkNTljNzY …

UHF-8833: Change Askem-features no-cookies texts

---

hdbt.theme

* Remove alt-text manipulation when caption or photographer information is available
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8691`
[UHF-8691]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8691: Remove alt-text manipulation when caption or photographer information is available

---

hdbt.libraries.yml
hdbt.theme

* Change the way to load EU cookie compliance libraries to surpress the "The following theme is missing from the file system: eu_cookie_compliance".
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8650_pre_cleaning`
[UHF-8650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8650 Pre cleaning

---

src/js/embedded-content-cookie-compliance.js
src/js/matomo.js
templates/misc/embedded-content-cookie-compliance.twig

* We want to use new cookie banner
* Embeds were switched to new banner
* matomo was switched to new banner, but I was unable to test it.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8650_cookie_banner_activation`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/826
[UHF-8650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8650: Switch embeds and matomo to use hds cookie banner

---

hdbt.theme

* Handle cache tags in `_hdbt_set_image_style`.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10973`
* Make sure cache is not disabled in `local.{settings.php,services.yml}`.
[UHF-10973]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10973: Cache in _hdbt_set_image_style

---

hdbt.theme

This code:
```
Drupal::requestStack()->getCurrentRequest()?->attributes->get('exception');
```
returns the raw exception if maintenance mode is enabled, which causes `->getStatusCode()` to fail.
This resolves Sentry issue: https://sentry.hel.fi/organizations/city-of-helsinki/issues/36088.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X-fix-sentry-error`

Check exception type

---

src/images/favicon/manifest.webmanifest

We get favicon errors on main site due to urls being wrong
* Relative webmanifest file was fixed to be static
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X_webmanifest_fix`

UHF-X: Fix webmanifest favicon url

---

templates/field/field--paragraph--field-service-links--popular-service-item.html.twig
templates/misc/popular-service-item.twig
templates/misc/popular-service-links.twig
templates/paragraphs/paragraph--popular-service-item.html.twig

* Make the popular services templates reusable for Helsinki near you page purposes.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10773`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1132
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/793
[UHF-10773]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10773: Make the popular services templates reusable

---

hdbt.theme
templates/paragraphs/paragraph--unit-contact-card.html.twig
translations/fi.po
translations/sv.po

* Refactor the unit contact card logic on hdbt
* Replace the title display logic with the heading radiobutton selection
* Check installation instructions from the [helfi_platform_config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/876)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1142
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/876
[UHF-9507]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9507: Replace unit contact card title with a radio button selection

---

templates/content/external-entity--linkedevents-event.html.twig

* Add null check for the external event template
* Check installing instructions from the [helfi_platform_config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/895)
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/895
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1169

UHF-X: External event entity causes WSOD fix

---

hdbt.libraries.yml

A follow up on #1186 to update the accordion library version. Without it varnish keeps serving the old version.
* Accordion library version was updated
* Make sure your `drupal-helfi-sote`-instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11427_update_library_version`
[UHF-11427]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11427: Updating accordion library version

---

hdbt.libraries.yml

* Update school search library version to get changes past caches
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11231`
[UHF-11231]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11231: Update school search library version to get changes past caches

---

hdbt.info.yml

This change was made with command: sed -i '' 's/\^9 || \^10/^10 || ^11/g' **/*.yml
[UHF-11071]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mark modules D11 compatable

---

hdbt.theme

* Changed "Hae päätöksiä" link to be external in search bar
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11233`
[UHF-11233]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11233: Changed päätökset link to be external

---

hdbt.theme

* Fixed site information function
* Make sure your Avustukset instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-X-frontpage-url-fix`
[UHF-11431]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11431 Added += values to fix missing frontpage instance url

---

templates/component/unit-search.twig

* Added h2 for unit search title
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10494`
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/813
[UHF-10494]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-10494: Added h2 tag for unit search title

---

hdbt.theme

* Fix check if language switcher is on
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9700`
[UHF-9700]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9700: Fix check if language switcher is on

---

templates/component/content-list-with-count.twig

* Added check if title exists in content-list-with-count template
* Make sure your for example **SOTE** instance is up and running on latest dev branch.
* `make fresh`

Added check if title exists

---

hdbt.theme

* Changed the English toast_link_title to correct one
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-9700`
[UHF-9700]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-9700 Change the English toast_link_title to correct one

---

hdbt.theme
templates/misc/feed-icon.html.twig

* Added check if link_title already is set for feed icon (makes it possible to pass it as a variable)
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11292`
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/1069
[UHF-11292]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11292: Added check if link_title is already set

---

README.md

* Added documentation on stylelint usage.
* No installation needed.
[UHF-8751]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8751: Add documentation on how to use stylelint on themes

---

templates/module/helfi_tpr/tpr-unit-contact-information.html.twig
translations/fi.po
translations/sv.po

* Changed the label, icon and link text in TPR Unit contact information on Unit page. 
* Check installation instructions from the [helfi_platform_config PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/975).
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/975 
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1276
[UHF-11284]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-11284: Change website information row on TPR Units

---

templates/paragraphs/paragraph--phasing.html.twig

* Added check to phasing paragraph if wrapping element should be ol or ul
Test for example in etusivu
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-8899`
* Update the Helfi Platform config
* `composer require drupal/helfi_platform_config:dev-UHF-8899`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/997
[UHF-8899]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-8899: Added check if it should be ol or ul

---

hdbt.libraries.yml

For every JS lib that is 1) react lib 2) is not preprocessed, we replace version with HELFI_DEPLOYMENT_IDENTIFIER tag for helfi_api_base module.
Varnish cache clearing on purge removed in [this](https://github.com/City-of-Helsinki/drupal-module-helfi-proxy/pull/80) PR.
* libraries in hdbt now use  HELFI_DEPLOYMENT_IDENTIFIER instead of static version
* Varnish cache purge was removed from helfi_proxy module
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-10628`
* Add deploy id to `local.settings.php` 
* For example: `$settings['deployment_identifier'] = 'local-1234';`
* Build theme in the `public/themes/contrib/hdbt`:
* `nvm use; npm i; npm run …

UHF-10628: 

---

templates/paragraphs/paragraph--content-cards.html.twig
templates/paragraphs/paragraph--list-of-links.html.twig

* Added description fields for list of links and content cards
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-5038`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1019
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1306
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/1122
[UHF-5038]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-5038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UHF-5038: Added description fields for list of links and content cards
